### ISSUE TITLE
Suggested Improvements for Boat Piloting

### ISSUE THREAD

**Issue by Obscure2020** [CodeF53/CardinalIceBoats#1]
As we discussed on Discord, the original plan was to only allow snap-turn priming while riding on ice. However, due to small inconsistencies in when the turn ends up being carried out, we found through testing that it was quite possible to end up riding on the very edge of an ice block following a completed automatic snap-turn. When riding on the very edge of the block, the mod would now think we were riding not on ice but on _air,_ and subsequently unhelpfully disallow snap-turns.

Your temporary fix was to allow snap turning while riding on any block.

I propose two changes which, when implemented _together_, will allow for mod-assisted correction of sub-optimal riding placement and allow a reinstatement of the ice-only restriction.

**New Keybind: Snap Key**
While riding in a boat, pressing this key will snap your riding direction to the nearest cardinal direction.

**New Config Toggle: Ice Riding Restriction**
When set to `False`: Auto Snap-Turn priming and the Snap Key will always work while in a boat, regardless of what you're riding on.
When set to `True`: Auto Snap-Turn priming and the Snap Key will only work while riding a boat on ice.

---

My envisioned use-case goes like this:
I would likely always set **Ice Riding Restriction** to True. Then, while traveling on ice roads, if I notice that I am too close to the edge of the road following a snap-turn, I can use A or D to manually deviate my path of travel away from the edge of the block, then press the **Snap Key** to realign myself to a cardinal direction of travel.

---

While writing this, another possible change popped into my head. I don't feel that this is quite as necessary as the new ideas above, but you may consider it worth putting in anyway. Let me know what you think of this:

**New Config Toggle: 8-Direction Snap Key**
When set to `False`: Pressing the Snap Key will align you with the nearest North, West, South, or East.
When set to `True`: Pressing the Snap Key will align you with the nearest North, Northwest, West, Southwest, South, Southeast, East, or Northeast.

**Comment by CodeF53** [comment]
**New Keybind: Snap Key**
yes

**New Config Toggle: Ice Riding Restriction**
- adds loads of difficult to solve edge cases
- makes using the mod more difficult
- doesn't serve any benefit to the user

**Comment by Obscure2020** [comment]
I actually wanted the **8-Direction Snap Key** to be an _option_ because I actually wanted to limit it to 4 directions most of the time, but I could see other users wanting 8 directions or other servers making 8 directions necessary.
