### ISSUE TITLE
Turn Causes Crash

### ISSUE THREAD

**Issue by Jh16** [CodeF53/CardinalIceBoats#10]
For v1.2.4-1.19.3 Fabric.

I'm getting a crash when the mod activates on a turn.
Hopefully, the crash report gives you the info needed.

[crash-2022-12-12_21.54.21-client.txt](https://github.com/CodeF53/CardinalIceBoats/files/10214108/crash-2022-12-12_21.54.21-client.txt)

**Comment by Obscure2020** [comment]
I can corroborate this bug. I experienced it too.\
We have already identified an internal issue.\
Access Widener was not operating as expected, resulting in a `tried to access a private field` error.

The most recent release was only tested in the development environment.\
The error was created by a fault in the compile.\
Hence the error was not caught prior to release.

**Comment by CodeF53** [comment]
fixed, https://modrinth.com/mod/cardinalboats/version/1.2.4.1-1.19.3
