### ISSUE TITLE
Primed turns get stuck on walls

### ISSUE THREAD

**Issue by Balint817** [CodeF53/CardinalIceBoats#14]
When using primed turns, the boat ends up turning too early and getting stuck on railings

Edit: only occurs when railing is a full block, so using walls/fences works as a temp fix

**Comment by CodeF53** [comment]
The only way I can envision fixing this issue involves adding a load of checks that would make the turn priming system laggy and unreliable 

I will attempt to fix it, but no promises

**Comment by CodeF53** [comment]
The solution I came up with is "Smart Centering"
> scans ahead a configurable number of blocks for Walls either side of ice road
> if it sees a wall, it will "nudge" the boat over a bit so it doesn't hit it
> if it doesn't see a wall, it goes back to the center of the block

1. Smart Center Key (keybind - `\` by default)
> smart centers the boat

2. Smart Center Lookahead distance (modconfig - 5 by default)
> Number of blocks ahead of you that smart center will look for walls

3. Smart Center on primed turns (modconfig - on by default)
> If the boat will automatically smart center after taking a primed turn

4. Always Smart Center (modconfig - off by default)
> Runs smart center every tick when boat is perfectly cardinally aligned

https://github.com/CodeF53/CardinalIceBoats/assets/37855219/f67e7fc3-a1dc-4274-bfa1-182805d0a196

**Comment by CodeF53** [comment]
Will be closed when an update containing the feature is pushed to modrinth

**Comment by Balint817** [comment]
Thank you for the quick fix!

**Comment by CodeF53** [comment]
https://modrinth.com/mod/cardinalboats/version/1.4.0
