### ISSUE TITLE
[Feature Request] Reverse

### ISSUE THREAD

**Issue by Balint817** [CodeF53/CardinalIceBoats#15]
Title, it'd be great if we could turn back with the down arrow, for example

Edit: x%360-180

**Comment by CodeF53** [comment]
Good suggestion, I will definitely implement this next time I work on the mod

**Comment by CodeF53** [comment]
Will be closed when an update containing the feature is pushed to modrinth

**Comment by Balint817** [comment]
Thank you for the quick work here as well!

**Comment by CodeF53** [comment]
https://modrinth.com/mod/cardinalboats/version/1.4.0
