### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by verixyt3** [CodeF53/CardinalIceBoats#17]
Hello, I'm asking you to make a version for _1.20.2 fabric or quilt on Modrinth_, **thank you very much!**

**Comment by sternschnaube** [comment]
I tested the mod right now, it loads fine on Client and Server side.

Was not tested it's functionality yet - I think it can be marked as 1.20.2 compatible @CodeF53 😄

**Comment by CodeF53** [comment]
> I tested the mod right now, it loads fine on Client and Server side.
> 
> Was not testing it's functionality yet - I think it can be marked as 1.20.2 compatible @CodeF53 😄

Testing functionality is kinda important. The game instantly crashes when you place a boat.

**Comment by CodeF53** [comment]
Sorry about the wait.

**Comment by sternschnaube** [comment]
Ohh... I was indeed not even placing a boat and just checked the mod loading, my bad!!!!!

Thanks for pushing the update 😊
