### ISSUE TITLE
Enhancement: Chat while in Motion

### ISSUE THREAD

**Issue by Obscure2020** [CodeF53/CardinalIceBoats#7]
I don't know if it's possible to make this, but here's the idea:

The mod should watch for when you open the chat box by pressing `T`.
If you are riding in a boat AND you were actively holding down `W` when you press `T`, then the mod should continue "holding" `W` for you until the chat box is closed.

This way you could remain in motion while still being able to use the in-game chat.
(Especially useful when boating on a long straightaway.)

This should work while boating on any surface. No ice check.
This should, however, be configurable. A config option that defaults to `Off`, I think.
(I can supply config text and hovertext, as usual, if we get to that stage.)

(And this should go without saying, but I'll specify this anyway: the mod shouldn't rely on `W` or `T` literally. It should still work if the user has remapped the `Forward` and `Open Chat` keys.)

**Comment by CodeF53** [comment]
Definitely possible

I will have a look at how invmove does movement when a screen is open for reference.

https://github.com/PieKing1215/InvMove/blob/e1c6e4334a7cd85976d3f679dfed5161a4aaa9c6/common/src/main/java/me/pieking1215/invmove/InvMove.java#L252

**Comment by Obscure2020** [comment]
Okay, cool.

Remember, I'm not asking for steering or turn priming or snap key support, just sustained forward movement.
Keep this one simple.

**Comment by CodeF53** [comment]
Added and released in 1.3.0
