### ISSUE TITLE
Cosmetic Improvement: Custom-Text Button

### ISSUE THREAD

**Issue by Obscure2020** [CodeF53/CardinalIceBoats#8]
We've discussed this idea before.
I understand if this takes a long time to figure out.
That's okay. This is totally nonessential, just a nice-to-have.

The **Eight-Way Snap Key** option would be reformatted. Here's the specs:

New title:
**Snap Key Directionality**

Changed button options:
`Yes` gets changed to `Eight-Way`
`No` gets changed to `Four-Way`

New hovertext:
```
Eight-Way - Pressing Snap Key will align boat to nearest 45°
Four-Way - Pressing Snap Key will align boat to nearest 90°
```

**Comment by CodeF53** [comment]
Pretty sure this would require me to switch from Autoconfig, but I will look further into it.

**Comment by CodeF53** [comment]
https://github.com/CodeF53/CardinalIceBoats/commit/ef91a6f052a6fd650c7df96f05e1bd88ecd4b56a

![image](https://user-images.githubusercontent.com/37855219/181082187-b1fca291-1411-49ed-a611-2bab65de9584.png)
![image](https://user-images.githubusercontent.com/37855219/181082282-cc623ca2-0d16-4304-ad3c-a0d1ef9f9905.png)

Done!
I will release this on modrinth once I solve your other issue.

**Comment by Obscure2020** [comment]
Dude! Awesome!
Taking a look at the config, I'm glad to see this wasn't too hard to pull off!

**Comment by Obscure2020** [comment]
Hey, actually, looking further at the screenshot you have provided as well as the new config text added in the latest commit, I think a coloring change is in order.

See, we color-coded `Yes` and `No` in the hovertext red and green to correspond with the default styling of text on the default yes/no button. Now that the button _doesn't_ look that way anymore, I'd like to propose a new color scheme:

Cyan for `Eight-Way` and Orange for `Four-Way`.
Why these colors? Because Red and Green are a famous duopoly, and as the _Portal_ games proved, so are Cyan and Orange.

Here's the `json` implementation:
```json
"text.autoconfig.CardinalBoat.option.eightWaySnapKey.@Tooltip" : "§bEight-Way§r - Pressing Snap Key will align boat to nearest 45°\n§6Four-Way§r - Pressing Snap Key will align boat to nearest 90°",
"text.autoconfig.CardinalBoat.option.eightWaySnapKey.boolean.true" : "§bEight-Way",
"text.autoconfig.CardinalBoat.option.eightWaySnapKey.boolean.false" : "§6Four-Way",
```

**Comment by CodeF53** [comment]
https://github.com/CodeF53/CardinalIceBoats/commit/5dc2a71901d688d4f78ed20f85259fd5769ed7dc

**Comment by Obscure2020** [comment]
Excellent!

**Comment by CodeF53** [comment]
https://modrinth.com/mod/cardinalboats/version/1.2.4-1.19.3
